openapi: 3.0.0
info:
  title: Organization API
  version: 1.0.0
  description: API for managing organizations
paths:
  /organization:
    post:
      summary: Add organization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                organization_id:
                  type: string
                shop_id:
                  type: string
                  pattern: ^shop[0-9]+$
                  example: shop001
                shop_name:
                  type: string
                  example: Example Shop
      responses:
        '200':
          description: Successful operation
        '404':
          description: Not found
        '500':
          description: Internal server error
  /shop:
    post:
      summary: Add shop
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                shop_id:
                  type: string
                  pattern: ^shop[0-9]+$
                  example: shop001
                  default: shop001
                shop_name:
                  type: string
                  example: Example Shop
      responses:
        '200':
          description: Successful operation
        '404':
          description: Not found
        '500':
          description: Internal server error
        # Additional response types can be added here if needed
servers:
  - url: http://api.example.com/v1