openapi: 3.0.0
info:
  title: Organization API
  version: 1.0.0
  description: API for managing organizations
paths:
  /organization:
    post:
      summary: Add organization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                organization_id:
                  type: string
                shop_id:
                  type: string
                  example: shop001
                shop_name:
                  type: string
                  example: Example Shop
      responses:
        '200':
          description: Successful operation
        '404':
          description: Not found
        '500':
          description: Internal server error
  /organization/{organization_id}:
    get:
      summary: Get organization by ID
      parameters:
        - name: organization_id
          in: path
          required: true
          description: ID of the organization to get
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '404':
          description: Organization not found
        '500':
          description: Internal server error
    put:
      summary: Update organization
      parameters:
        - name: organization_id
          in: path
          required: true
          description: ID of the organization to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                organization_name:
                  type: string
      responses:
        '200':
          description: Successful operation
        '404':
          description: Organization not found
        '500':
          description: Internal server error
  /shop:
    post:
      summary: Add shop
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                shop_id:
                  type: string
                  example: shop001
                shop_name:
                  type: string
                  example: Example Shop
      responses:
        '200':
          description: Successful operation
        '404':
          description: Not found
        '500':
          description: Internal server error
components: {}
servers:
  - url: http://api.example.com/v1