openapi: 3.0.0
info:
  title: Organization API
  version: 1.0.0
  description: API for managing organizations
paths:
  /organization:
    post:
      summary: Add organization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                organization_id:
                  type: string
      responses:
        '200':
          description: Successful operation
        '404':
          description: Not found
        '500':
          description: Internal server error